Version: '2020-06-01'
Type: Resource
ResourceType:
  From: alicloud_cdn_domain_config
  To: ALIYUN::CDN::DomainConfig
Properties:
  config_id:
    Ignore: true
  domain_name:
    To: DomainNames
  function_args:
    Ignore: true
  function_name:
    Ignore: true
  status:
    Ignore: true
Attributes:
  id:
    Ignore: true
  config_id:
    Ignore: true
  domain_name:
    Ignore: true
  function_args:
    Ignore: true
  function_name:
    Ignore: true
  status:
    Ignore: true
